"""
RankAlpha — product page (demo). RankAlpha Phase 8.

Streamlit front-end over the frozen model + Phase-7 pie engine. LONG-ONLY, risk-managed,
self-explaining. EDUCATIONAL SIMULATION ONLY — not investment advice.

Run:
    streamlit run app.py
"""

import os

import streamlit as st

from portfolio.engine import score_book, finalize_portfolio, cash_fraction
from portfolio.llm_explainer import explain
from portfolio.paper_trade import load_track, compute_stats

st.set_page_config(page_title="RankAlpha (demo)", page_icon="📊", layout="wide")

# Bridge Streamlit secrets -> env so the LLM explainer (which reads os.environ) picks up
# GROQ_API_KEY on a hosted deploy. The key lives only in Streamlit secrets / env — never
# in the repo. No-op locally if no secrets file is present.
try:
    for _k in ("GROQ_API_KEY", "GROQ_MODEL"):
        if _k in st.secrets and _k not in os.environ:
            os.environ[_k] = str(st.secrets[_k])
except Exception:  # no secrets.toml configured -> stay on local/template path
    pass

DISCLAIMER = ("⚠️ **EDUCATIONAL SIMULATION — NOT investment advice. No real money. "
              "Past backtest does NOT predict future returns.**")

# Risk slider label -> annualized vol target.
RISK_LEVELS = {"Conservative": 0.10, "Balanced": 0.14, "Aggressive": 0.20}


@st.cache_resource(show_spinner="Loading the frozen ranker (cached on disk after first run)…")
def get_book(top_n=50, max_weight=0.08):
    """Expensive, target-vol-independent scoring. Cached for the session AND to disk
    (joblib) by the engine, so a fresh run loads in milliseconds instead of refitting."""
    return score_book(top_n=top_n, max_weight=max_weight)


def render_builder(book):
    """Tab 1 — build a fresh pie for an amount + risk level (uses the cached book)."""
    book_vol = book["book_vol"]

    # ---- Inputs ----
    left, right = st.columns([1, 2])
    with left:
        amount = st.number_input("Investment amount ($)", min_value=100, max_value=10_000_000,
                                 value=10_000, step=500)
        risk = st.select_slider("Risk level", options=list(RISK_LEVELS), value="Balanced")
        target_vol = RISK_LEVELS[risk]

        # Live tradeoff: cash % updates instantly with the slider (no refit).
        cash_pct = cash_fraction(book_vol, target_vol) * 100
        st.metric("Target volatility", f"{target_vol*100:.0f}%")
        st.metric("Invested vs cash", f"{100-cash_pct:.0f}% invested",
                  f"-{cash_pct:.0f}% held as cash", delta_color="off")
        st.caption(f"The selected long book has an estimated **{book_vol*100:.0f}%** "
                   f"annualized volatility. To hit your {target_vol*100:.0f}% target we "
                   f"hold {cash_pct:.0f}% cash (we never use leverage). More risk → more "
                   f"invested, less cash.")
        go = st.button("Build my pie", type="primary", width="stretch")

    if not go:
        st.info("Set an amount and risk level, then **Build my pie**.")
        return

    # ---- Build the pie with staged progress feedback ----
    with st.status("Building your pie…", expanded=True) as status:
        st.write("⚙️ Sizing the book and rendering figures…")
        p = finalize_portfolio(book, amount, target_vol)
        r = p["risk_stats"]

        if os.environ.get("GROQ_API_KEY"):
            backend_msg = "(Groq cloud LLM)…"
        elif os.environ.get("USE_LLM") == "1":
            backend_msg = "(local Phi-3)…"
        else:
            backend_msg = "(instant template)…"
        st.write("🧠 Generating plain-English explanation " + backend_msg)
        summary = explain(p)
        status.update(label="Pie ready ✓", state="complete", expanded=False)

    # ---- LLM explainer ----
    st.subheader("Why this portfolio looks like this")
    st.write(summary["text"])
    st.caption(f"_Explanation generated by: {summary['source']} "
               f"(facts come only from the model; the text invents no numbers)._")

    # ---- Pie + risk ----
    c1, c2 = st.columns([3, 2])
    with c1:
        st.subheader(f"Allocation — ${amount:,.0f} as of {p['as_of']}")
        st.image(p["figures"]["pie"], width="stretch")
    with c2:
        st.subheader("Honest risk panel")
        st.caption("Backtested on the long-only book, 2022–2026 out-of-sample.")
        st.metric("Backtested annualized volatility", f"{r['ann_vol']*100:.1f}%")
        st.metric("Historical max drawdown", f"{r['max_drawdown']*100:.1f}%")
        st.metric("Monthly return range (5–95th pct)",
                  f"{r['monthly_ret_p05']*100:+.1f}% to {r['monthly_ret_p95']*100:+.1f}%")
        st.warning("These are **HISTORICAL** figures from a backtest — **not a forecast** "
                   "and not a probability.")

    # ---- Holdings table ----
    st.subheader("Holdings — each explains itself")
    rows = []
    for tk, w in p["weights"].items():
        ex = p["explanations"][tk]
        rows.append({
            "Ticker": tk,
            "$ Allocation": f"${p['dollar_allocations'][tk]:,.0f}",
            "Weight": f"{w*100:.1f}%",
            "Sector": ex.get("sector", "?"),
            "Why it's in the pie": "; ".join(ex.get("reasons", [])),
        })
    rows.append({"Ticker": "CASH", "$ Allocation": f"${p['dollar_allocations']['CASH']:,.0f}",
                 "Weight": f"{p['cash_weight']*100:.1f}%", "Sector": "—",
                 "Why it's in the pie": "Volatility-target buffer (no leverage)"})
    st.dataframe(rows, width="stretch", hide_index=True)

    with st.expander("Per-holding factor exposures (heatmap)"):
        st.image(p["figures"]["factors"], width="stretch")


def render_track():
    """Tab 2 — REALIZED, out-of-sample paper-trading track record (reads the ledger only;
    no model fit). The ledger is built/refreshed offline via `python -m portfolio.paper_trade`."""
    st.subheader("📈 Live paper-trading track record")
    pf, _ = load_track()
    if pf is None or not len(pf):
        st.info("No track record yet. Build it offline with "
                "`python -m portfolio.paper_trade` (one model fit, then it marks each "
                "month to realized returns).")
        return

    s = compute_stats(pf)
    b, bm = s["book"], s["benchmark"]
    st.caption(f"Model **frozen on {s['freeze_date']}** and never refit. Every month below "
               f"is **out-of-sample** — the ranker had not seen it. This is a *realized* "
               f"forward record, **not** the in-sample backtest and **not** a forecast.")

    if s["is_short_sample"]:
        st.warning(f"⚠️ Only **{s['n_months']} months** of out-of-sample paper trading — "
                   "too short to be statistically meaningful yet. Don't read a Sharpe into "
                   "this. The track grows by one month per real month elapsed.")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Annualized return", f"{b['ann_return']*100:+.1f}%",
              f"{s['excess_ann_return']*100:+.1f}% vs eq-wt", delta_color="off")
    c2.metric("Annualized vol (realized)", f"{b['ann_vol']*100:.1f}%")
    c3.metric("Max drawdown", f"{b['max_drawdown']*100:.1f}%")
    c4.metric("Hit rate (months up)", f"{b['hit_rate']*100:.0f}%")
    st.caption(f"Sharpe (rf=0) **{b['sharpe']:.2f}** vs equal-weight universe "
               f"**{bm['sharpe']:.2f}** · {s['n_months']} monthly rebalances "
               f"({s['inception']} → {s['latest']}).")

    st.image("figures/paper_track_equity.png", width="stretch")
    with st.expander("Honest stats card (book vs equal-weight benchmark)"):
        st.image("figures/paper_track_stats.png", width="stretch")


def main():
    st.title("📊 RankAlpha — transparent portfolio builder")
    st.error(DISCLAIMER)   # unmissable, top of page, red banner
    st.caption("A frozen LightGBM cross-sectional ranker picks the S&P 500 long book; "
               "sizing is inverse-volatility, position-capped, and volatility-targeted. "
               "Every holding explains itself. This is a methodology demo, not a product.")

    book = get_book()

    tab_build, tab_track = st.tabs(["🥧 Build a pie", "📈 Track record"])
    with tab_build:
        render_builder(book)
    with tab_track:
        render_track()

    st.divider()
    st.error(DISCLAIMER)   # repeat at the bottom — unmissable


if __name__ == "__main__":
    main()
