"""
RankAlpha — product page (demo). RankAlpha Phase 8.

Streamlit front-end over the frozen model + Phase-7 pie engine. LONG-ONLY, risk-managed,
self-explaining. EDUCATIONAL SIMULATION ONLY — not investment advice.

Run:
    streamlit run app.py
"""

import streamlit as st

from portfolio.engine import score_book, finalize_portfolio, cash_fraction
from portfolio.llm_explainer import explain

st.set_page_config(page_title="RankAlpha (demo)", page_icon="📊", layout="wide")

DISCLAIMER = ("⚠️ **EDUCATIONAL SIMULATION — NOT investment advice. No real money. "
              "Past backtest does NOT predict future returns.**")

# Risk slider label -> annualized vol target.
RISK_LEVELS = {"Conservative": 0.10, "Balanced": 0.14, "Aggressive": 0.20}


@st.cache_resource(show_spinner="Fitting the frozen ranker on history (one-time)…")
def get_book(top_n=50, max_weight=0.08):
    """Expensive, target-vol-independent scoring. Cached for the session."""
    return score_book(top_n=top_n, max_weight=max_weight)


def main():
    st.title("📊 RankAlpha — transparent portfolio builder")
    st.error(DISCLAIMER)   # unmissable, top of page, red banner
    st.caption("A frozen LightGBM cross-sectional ranker picks the S&P 500 long book; "
               "sizing is inverse-volatility, position-capped, and volatility-targeted. "
               "Every holding explains itself. This is a methodology demo, not a product.")

    book = get_book()
    book_vol = book["book_vol"]

    # ---- Inputs ----
    left, right = st.columns([1, 2])
    with left:
        amount = st.number_input("Investment amount ($)", min_value=100, max_value=10_000_000,
                                 value=10_000, step=500)
        risk = st.select_slider("Risk level", options=list(RISK_LEVELS), value="Balanced")
        target_vol = RISK_LEVELS[risk]

        # Live tradeoff: cash % updates instantly with the slider (no refit).
        cash_pct = cash_fraction(book_vol, target_vol) * 100
        st.metric("Target volatility", f"{target_vol*100:.0f}%")
        st.metric("Invested vs cash", f"{100-cash_pct:.0f}% invested",
                  f"-{cash_pct:.0f}% held as cash", delta_color="off")
        st.caption(f"The selected long book has an estimated **{book_vol*100:.0f}%** "
                   f"annualized volatility. To hit your {target_vol*100:.0f}% target we "
                   f"hold {cash_pct:.0f}% cash (we never use leverage). More risk → more "
                   f"invested, less cash.")
        go = st.button("Build my pie", type="primary", use_container_width=True)

    if not go:
        st.info("Set an amount and risk level, then **Build my pie**.")
        return

    p = finalize_portfolio(book, amount, target_vol)
    r = p["risk_stats"]

    # ---- LLM explainer ----
    with st.spinner("Generating plain-English explanation (local Phi-3)…"):
        summary = explain(p)
    st.subheader("Why this portfolio looks like this")
    st.write(summary["text"])
    st.caption(f"_Explanation generated by: {summary['source']} "
               f"(facts come only from the model; the text invents no numbers)._")

    # ---- Pie + risk ----
    c1, c2 = st.columns([3, 2])
    with c1:
        st.subheader(f"Allocation — ${amount:,.0f} as of {p['as_of']}")
        st.image(p["figures"]["pie"], use_container_width=True)
    with c2:
        st.subheader("Honest risk panel")
        st.caption("Backtested on the long-only book, 2022–2026 out-of-sample.")
        st.metric("Backtested annualized volatility", f"{r['ann_vol']*100:.1f}%")
        st.metric("Historical max drawdown", f"{r['max_drawdown']*100:.1f}%")
        st.metric("Monthly return range (5–95th pct)",
                  f"{r['monthly_ret_p05']*100:+.1f}% to {r['monthly_ret_p95']*100:+.1f}%")
        st.warning("These are **HISTORICAL** figures from a backtest — **not a forecast** "
                   "and not a probability.")

    # ---- Holdings table ----
    st.subheader("Holdings — each explains itself")
    rows = []
    for tk, w in p["weights"].items():
        ex = p["explanations"][tk]
        rows.append({
            "Ticker": tk,
            "$ Allocation": f"${p['dollar_allocations'][tk]:,.0f}",
            "Weight": f"{w*100:.1f}%",
            "Sector": ex.get("sector", "?"),
            "Why it's in the pie": "; ".join(ex.get("reasons", [])),
        })
    rows.append({"Ticker": "CASH", "$ Allocation": f"${p['dollar_allocations']['CASH']:,.0f}",
                 "Weight": f"{p['cash_weight']*100:.1f}%", "Sector": "—",
                 "Why it's in the pie": "Volatility-target buffer (no leverage)"})
    st.dataframe(rows, use_container_width=True, hide_index=True)

    with st.expander("Per-holding factor exposures (heatmap)"):
        st.image(p["figures"]["factors"], use_container_width=True)

    st.divider()
    st.error(DISCLAIMER)   # repeat at the bottom — unmissable


if __name__ == "__main__":
    main()
