#!/usr/bin/env python3
"""
Regenerate RankAlpha's honest performance scorecard — Phase 13.

Runs the Phase 12 base analyser on RankAlpha's **committed** forward paper-track
returns (`data/paper_track_portfolio.parquet`) and regenerates:

  * `figures/analytics/rankalpha_scorecard.md`   — the metric scorecard (book vs benchmark)
  * `figures/analytics/rankalpha_{equity,drawdown,rolling,hist,overlay}.png`

No refit, no network: this only READS the frozen model's committed ledger. yfinance is
never imported. Run it any time to reproduce the report from data already in the repo.

    python scripts/analyse.py        # or:  make analyse
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

# Make the repo root importable whether run as `python scripts/analyse.py` or `-m`.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from analytics.metrics import analyse  # noqa: E402
from analytics.rankalpha import rankalpha_returns, report, PERIODS_PER_YEAR  # noqa: E402

SCORECARD_PATH = Path("figures/analytics/rankalpha_scorecard.md")


def _pct(x: float) -> str:
    return "—" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:.2%}"


def _num(x: float) -> str:
    return "—" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:.2f}"


def build_scorecard() -> str:
    book, bench = rankalpha_returns()
    n = len(book)
    b = analyse(book, benchmark=bench, periods_per_year=PERIODS_PER_YEAR)
    k = analyse(bench, benchmark=bench, periods_per_year=PERIODS_PER_YEAR)

    # Reconcile the analyser (population std, ddof=0) with the paper-trade eval and
    # README (sample std, ddof=1). The only difference is n vs n-1: multiply a
    # ddof=0 Sharpe by sqrt((n-1)/n) to recover the ddof=1 figure.
    ddof1 = math.sqrt((n - 1) / n)
    book_sharpe_ddof1 = b["sharpe"] * ddof1
    bench_sharpe_ddof1 = k["sharpe"] * ddof1

    rows = [
        ("Total return", _pct(b["total_return"]), _pct(k["total_return"])),
        ("CAGR (annualised)", _pct(b["cagr"]), _pct(k["cagr"])),
        ("Volatility (annualised, ddof=0)", _pct(b["volatility"]), _pct(k["volatility"])),
        ("Sharpe (rf=0, ddof=0)", _num(b["sharpe"]), _num(k["sharpe"])),
        ("Sortino (rf=0, ddof=0)", _num(b["sortino"]), _num(k["sortino"])),
        ("Max drawdown", _pct(b["max_drawdown"]), _pct(k["max_drawdown"])),
        ("Max drawdown duration (months)", str(b["max_drawdown_duration"]),
         str(k["max_drawdown_duration"])),
        ("Hit rate (positive months)", _pct(b["hit_rate"]), _pct(k["hit_rate"])),
        ("Beta (vs equal-weight universe)", _num(b["beta"]), "1.00"),
        ("Alpha (annualised)", _pct(b["alpha"]), "0.00%"),
    ]

    lines = [
        "# RankAlpha — analyser scorecard (forward paper track)",
        "",
        "*Auto-generated by `scripts/analyse.py` (Phase 13). Educational SIMULATION only — "
        "regenerated from committed data, no refit, no network.*",
        "",
        f"Model frozen **2024-05-15**, traded forward **{n} months**, never refit. "
        "Benchmark is the **equal-weight investable universe** recorded alongside the book "
        "(`bench_ret`), NOT SPY — matching how the paper track defines its benchmark. "
        "Alpha/beta are reported together and are only meaningful against this benchmark.",
        "",
        "| Metric | Paper book | Equal-weight universe |",
        "|---|---|---|",
    ]
    lines += [f"| {name} | {bk} | {bn} |" for name, bk, bn in rows]

    lines += [
        "",
        "## Reconciliation with the prior eval",
        "",
        "The analyser uses **population** std (ddof=0) so its hand-check "
        "`vol([+12%,−8%,+4%,+8%]) = 7.48%` holds; `portfolio/paper_trade.py` and the README "
        "table use **sample** std (ddof=1). The two differ only by the n vs n−1 factor "
        f"√((n−1)/n) = √({n - 1}/{n}) = {ddof1:.4f}:",
        "",
        f"* Book Sharpe: {b['sharpe']:.2f} (ddof=0) × {ddof1:.4f} = "
        f"**{book_sharpe_ddof1:.2f}** ≈ README **1.25** ✅",
        f"* Benchmark Sharpe: {k['sharpe']:.2f} (ddof=0) × {ddof1:.4f} = "
        f"**{bench_sharpe_ddof1:.2f}** ≈ README **1.21** ✅",
        "",
        "Same numbers, different std convention — both trustworthy.",
        "",
        "## Caveats",
        "",
        "* **Survivorship-inflated:** absolute levels are not point-in-time; trust the "
        "*relative* (book vs same-universe benchmark) comparison, not the absolute Sharpe.",
        f"* **Too short:** {n} months is not statistically meaningful. No Sharpe-flexing.",
        "",
        "## Charts",
        "",
        "![equity](rankalpha_equity.png)",
        "![drawdown](rankalpha_drawdown.png)",
        "![rolling](rankalpha_rolling.png)",
        "![histogram](rankalpha_hist.png)",
        "![overlay](rankalpha_overlay.png)",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    md = build_scorecard()
    SCORECARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCORECARD_PATH.write_text(md, encoding="utf-8")

    rep = report(make_figs=True)  # regenerate the 5 charts from committed data
    m = rep["metrics"]

    print(f"Scorecard  -> {SCORECARD_PATH}")
    print(f"{rep['n_months']} months | Sharpe {m['sharpe']:.2f} (ddof=0) | "
          f"CAGR {m['cagr']:.1%} | maxDD {m['max_drawdown']:.1%} | "
          f"alpha {m['alpha']:.1%} | beta {m['beta']:.2f}")
    for name, path in rep["figures"].items():
        print(f"  figure {name:9s} -> {path}")


if __name__ == "__main__":
    main()
