"""
Phase 20 — sector-mapping report + cap-binding evidence.

Writes `figures/lab/sector_mapping.md`: coverage (A/B/missing), the universe sector
distribution, and for the wide-universe pie at β0.75 and β1.0 the sector concentration
BEFORE the caps (natural top-20 by score) vs AFTER (the shipped capped pie) — so the caps
are shown to be BINDING, not inert. Offline once the sectors file + wide parquets exist; no
refit (score_book is cached).
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import pandas as pd

from portfolio.engine import score_book
from portfolio.beta_engine import (
    build_portfolio, _load_sector_map, _monthly_returns, MIN_HISTORY,
)

PANEL = "data/midlarge_panel.parquet"
TICKERS = "data/universe_midlarge.csv"
FEATURES = "data/midlarge_features.parquet"
LABELED = "data/midlarge_labeled.parquet"
SECTORS_CSV = Path("data/universe_midlarge_sectors.csv")
OUT = Path("figures/lab/sector_mapping.md")
TOP_N = 20
NAME_SECTOR_CAP = 5
WT_SECTOR_CAP = 0.30


def _eligible_ranked():
    """The candidate names build_portfolio would pick from, ranked by score — i.e. names with
    a stable beta (≥ MIN_HISTORY monthly obs). This is the pre-cap selection pool."""
    book = score_book(top_n=max(TOP_N * 3, 50), features_path=FEATURES,
                      labeled_path=LABELED, panel_path=PANEL)
    panel = pd.read_parquet(PANEL); panel["date"] = pd.to_datetime(panel["date"])
    bench = _monthly_returns(panel).mean(axis=1, skipna=True)
    cand = list(book["holdings"]["ticker"])
    rets = _monthly_returns(panel, cand)
    eligible = [tk for tk in cand
                if tk in rets and rets[tk].dropna().shape[0] >= MIN_HISTORY]
    ranked = (book["holdings"][book["holdings"]["ticker"].isin(eligible)]
              .sort_values("model_score", ascending=False))
    return ranked, book


def _uncapped_sectors(ranked, sector_map) -> list[str]:
    """Natural top-N by score, NO sector cap — the 'before' book."""
    picked = list(ranked["ticker"].head(TOP_N))
    return [str(sector_map.get(tk, "?")) for tk in picked]


def _sector_weight(slices: dict) -> dict:
    by = {}
    for sl in slices.values():
        by[sl["sector"]] = by.get(sl["sector"], 0.0) + sl["weight"]
    return by


def build_report() -> Path:
    df = pd.read_csv(SECTORS_CSV)
    n = len(df)
    a = int((df["source"] == "A").sum())
    b = int((df["source"] == "B").sum())
    miss = df[df["source"] == "missing"]

    sector_map = _load_sector_map(TICKERS)
    ranked, _ = _eligible_ranked()

    L = []
    L.append("# RankAlpha — wide-universe sector mapping (Phase 20)\n")
    L.append("*Auto-generated by `scripts/sector_report.py`. Educational plumbing only — no "
             "model, no refit, no scoring. Regenerated from committed data.*\n")

    L.append("## ⚠️ Caveat (same class as survivorship)\n")
    L.append("Sector labels are **TODAY's** classification applied backwards. Reclassification "
             "is rare but nonzero; these labels exist only to keep the pie's caps from "
             "clustering correlated names — they are not point-in-time GICS.\n")

    L.append("## Coverage\n")
    L.append(f"- Total names: **{n}**")
    L.append(f"- Source A (yfinance `.info`): **{a}** ({a / n * 100:.1f}%)")
    L.append(f"- Source B (SEC SIC fallback): **{b}** ({b / n * 100:.1f}%)")
    L.append(f"- Labelled: **{n - len(miss)}** ({(n - len(miss)) / n * 100:.1f}%) · "
             f"Missing: **{len(miss)}**")
    if len(miss):
        L.append(f"- Missing tickers: {', '.join(miss['ticker'].tolist())}")
    L.append("")
    L.append("### Universe sector distribution\n")
    L.append("| Sector | Names |")
    L.append("|---|---|")
    for sec, c in df["sector"].value_counts().items():
        L.append(f"| {sec} | {c} |")
    L.append("")

    L.append("## Cap-binding kill-test — β0.75 and β1.00\n")
    L.append("For each pie: sector concentration of the **natural top-20 by score (no caps)** "
             "vs the **shipped capped pie**. Caps: ≤5 names/sector, ≤30% weight/sector.\n")
    for tb in (0.75, 1.00):
        p = build_portfolio(10_000, target_beta=tb, top_n=TOP_N, panel_path=PANEL,
                            tickers_path=TICKERS, features_path=FEATURES,
                            labeled_path=LABELED, make_figures=False)
        secs_after = [sl["sector"] for sl in p["slices"].values()]
        secs_before = _uncapped_sectors(ranked, sector_map)
        cnt_b, cnt_a = Counter(secs_before), Counter(secs_after)
        wt_a = _sector_weight(p["slices"])

        top_b_sec, top_b_n = cnt_b.most_common(1)[0]
        top_a_sec, top_a_n = cnt_a.most_common(1)[0]
        clipped = sorted({s for s in cnt_b if cnt_b[s] > NAME_SECTOR_CAP})

        L.append(f"### β{tb:.2f}\n")
        L.append(f"- '?' holdings in the capped pie: **{secs_after.count('?')}** "
                 f"(must be 0 → caps no longer inert)")
        L.append(f"- Max names/sector — before: **{top_b_n}** ({top_b_sec}) → "
                 f"after: **{top_a_n}** ({top_a_sec})  ⟶ cap {'BINDING' if top_b_n > NAME_SECTOR_CAP else 'slack'}")
        L.append(f"- Max weight/sector — after: **{max(wt_a.values()) * 100:.1f}%** "
                 f"(cap 30%)")
        if clipped:
            L.append(f"- Sectors the ≤5-name cap clipped: "
                     + ", ".join(f"{s} ({cnt_b[s]}→≤5)" for s in clipped))
        L.append("")
        L.append("| Sector | Before (no caps) | After (capped) | After weight |")
        L.append("|---|---|---|---|")
        for sec in sorted(set(cnt_b) | set(cnt_a), key=lambda s: -cnt_a.get(s, 0)):
            L.append(f"| {sec} | {cnt_b.get(sec, 0)} | {cnt_a.get(sec, 0)} | "
                     f"{wt_a.get(sec, 0) * 100:.1f}% |")
        L.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L))
    return OUT


def main():
    path = build_report()
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
