"""
The ML's Last Stand — RankAlpha #31. Three arms, one month, then the question closes.

⚠️ EDUCATIONAL SIMULATION. Survivorship-biased universe; every number is DIRECTIONAL.

Pre-stated success criterion (#31, fixed before any arm ran)
-----------------------------------------------------------
    A challenger earns the product engine ONLY by beating 12-1 momentum on the long-only
    top-20 book under the #27 duel rules: after-cost Sharpe AND a consistent Rank IC
    advantage (a majority of calendar years). Anything less: momentum keeps the engine,
    permanently.

Arms
----
1. **v2 clean LGBM** — A-1 fixed (`size` = raw traded `close`, never retro-adjusted),
   retrained with identical architecture, hyperparameters, features, label, walk-forward
   schedule and embargo. The shipped v1 is untouched and remains the historical record.
2. **XGBoost** — one controlled rival on identical features/labels/protocol, answering
   "is it the library?". AdaBoost is deliberately excluded (superseded family).
3. **Long/short research book** — the ML's natural vehicle, tracked as research only; the
   retail pie stays long-only by product definition.

This module owns arm 1. Arms 2 and 3 append to the same report after their own triage.
"""
from __future__ import annotations

from pathlib import Path

from lab.signal_duel import (
    BOOK_A, MIN_CONSISTENCY, OOS_PATH, _n, _p, _row, run as duel_run,
)

OOS_V1 = OOS_PATH
OOS_V2 = Path("data/sp500_oos_walkforward_v2.parquet")
REPORT_PATH = Path("figures/lab/last_stand.md")

V1_LABEL = "B · v1 ML (A-1 contaminated)"
V2_LABEL = "B · v2 ML (A-1 fixed)"


def arm1(make_report: bool = True) -> dict:
    """Rematch the duel with the A-1-fixed model, against the identical momentum control."""
    v1 = duel_run(make_report=False, oos_path=OOS_V1, ml_label=V1_LABEL)
    v2 = duel_run(make_report=False, oos_path=OOS_V2, ml_label=V2_LABEL)
    result = {"v1": v1, "v2": v2, "verdict": v2["verdict"]}
    if make_report:
        result["report_path"] = str(write_report(result))
    return result


def write_report(result: dict) -> Path:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    v1, v2 = result["v1"], result["v2"]
    ver = v2["verdict"]
    mom1, mom2 = v1["full"][BOOK_A], v2["full"][BOOK_A]
    ml1, ml2 = v1["full"][V1_LABEL], v2["full"][V2_LABEL]
    ic1, ic2 = v1["full_ic"][V1_LABEL], v2["full_ic"][V2_LABEL]
    momic = v2["full_ic"][BOOK_A]

    L = []
    L.append("# The ML's Last Stand (#31) — one month, pre-registered, then the question closes\n")
    L.append("*Auto-generated by `lab/last_stand.py`. ⚠️ **EDUCATIONAL SIMULATION** — nothing "
             "here is advice, and the universe is survivorship-biased, so every number is "
             "DIRECTIONAL.*\n")

    L.append("## The criterion, fixed before any arm ran\n")
    L.append("> A challenger earns the product engine **only** by beating 12-1 momentum on "
             "the long-only top-20 book under the #27 duel rules — after-cost Sharpe **AND** "
             "a consistent Rank IC advantage (a majority of calendar years). **Anything "
             "less: momentum keeps the engine, permanently.**\n")
    L.append(f"\"Consistent\" is fixed as beating momentum's Rank IC in more than "
             f"{MIN_CONSISTENCY:.0%} of calendar years. Applied as arithmetic by "
             "`signal_duel.decide()`, not as a judgement after the fact.\n")

    # ------------------------------------------------------------------ arm 1
    L.append("---\n")
    L.append("## Arm 1 — v2 clean LGBM (A-1 fixed)\n")
    L.append("**The one change.** `size` was `log(adj_close)`: a retroactively re-written "
             "series, so its value at a past date moved whenever a later split or dividend "
             "landed (#25 finding **A-1**). It is now `log(close)` — the price that actually "
             "traded that day, never rewritten. Raw close was chosen over point-in-time "
             "market cap deliberately: it keeps v2 a **one-variable** change from v1, which "
             "is what makes this rematch attributable. Architecture, hyperparameters, feature "
             "list, label, walk-forward schedule and 21-day embargo are all unchanged.\n")
    L.append("The shipped v1 model and its stored predictions were **not touched** — they are "
             "the historical record. v2 writes to its own `*_v2` artifacts, and the build "
             "asserts v1's feature table mtime is unchanged before it exits.\n")

    L.append(f"### Result — {v2['n_months']} walk-forward OOS months, {v2['window']}\n")
    L.append("| Book | n | Ann. return | Ann. vol | Sharpe | Sortino | MaxDD | Mean Rank IC | t |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    L.append(_row(BOOK_A + " *(control)*", mom2, momic))
    L.append(_row(V1_LABEL, ml1, ic1))
    L.append(_row(V2_LABEL, ml2, ic2))
    L.append("")
    L.append("| Book | Mean monthly turnover |")
    L.append("|---|---|")
    L.append(f"| {BOOK_A} | {_p(v2['turnover'][BOOK_A])} |")
    L.append(f"| {V1_LABEL} | {_p(v1['turnover'][V1_LABEL])} |")
    L.append(f"| {V2_LABEL} | {_p(v2['turnover'][V2_LABEL])} |")
    L.append("")

    L.append("### Verdict — momentum keeps the engine\n")
    L.append(f"* After-cost Sharpe: momentum **{_n(mom2['sharpe'])}** vs v2 "
             f"**{_n(ml2['sharpe'])}** → challenger wins on Sharpe: "
             f"**{'YES' if ver['ml_wins_sharpe'] else 'NO'}**")
    L.append(f"* Rank IC consistency: v2 beat momentum in **{len(ver['ic_years_won_by_ml'])} of "
             f"{ver['n_years']}** years ({ver['ic_consistency']:.0%}) → consistent: "
             f"**{'YES' if ver['ic_consistent'] else 'NO'}**")
    L.append(f"* **Earns the product engine: {'YES' if ver['ml_earns_keep'] else 'NO'}**\n")

    # ------------------------------------------------------------------ the finding
    d_sharpe = ml2["sharpe"] - ml1["sharpe"]
    d_ic = ic2["mean_ic"] - ic1["mean_ic"]
    L.append("### The finding: A-1 was never carrying the ML\n")
    L.append("This is the arm that was supposed to give the ML its fairest possible shot, and "
             "the honest headline is how **little** the fix changed:\n")
    L.append("| | v1 (contaminated) | v2 (clean) | Δ |")
    L.append("|---|---|---|---|")
    L.append(f"| After-cost Sharpe | {_n(ml1['sharpe'])} | {_n(ml2['sharpe'])} | "
             f"{d_sharpe:+.3f} |")
    L.append(f"| Mean Rank IC | {_n(ic1['mean_ic'], 4)} | {_n(ic2['mean_ic'], 4)} | "
             f"{d_ic:+.4f} |")
    L.append(f"| Turnover | {_p(v1['turnover'][V1_LABEL])} | {_p(v2['turnover'][V2_LABEL])} | |")
    L.append("")
    L.append("Rank IC moved **down** slightly on the clean feature, which is the direction a "
             "removed leak should move it — the contamination was worth a sliver of spurious "
             "ranking skill. Sharpe moved *up* slightly. Both moves are far smaller than the "
             "gap to momentum, and neither changes any verdict.\n")

    L.append("**This closes the asymmetric ruling, and it closes it cleanly.** #28 fixed the "
             "reading in advance: *ML loses ⇒ conclusive; ML wins ⇒ inconclusive pending a "
             "clean retrain.* The #30 duel was an ML loss, so it was already conclusive — but "
             "the caveat \"a clean model might do better\" remained technically open. It is "
             "now closed by measurement rather than by argument: **the clean model does not "
             "do better in any way that matters.** No contamination caveat survives on this "
             "question.\n")
    L.append("Worth stating plainly because it cuts against my own earlier framing: the "
             "asymmetric ruling was the right discipline, and the thing it was guarding "
             "against turned out not to exist. That is what a correctly-specified control "
             "looks like when it comes back negative.\n")

    L.append("### Consequences already applied\n")
    L.append("* `size` is fixed in `utils/sp500_features.py` — the leak is closed for every "
             "future build, not just for v2.\n")
    L.append("* The two A-1 tripwire tests **flipped as designed** and have been rewritten to "
             "assert the fixed behaviour, plus a third that checks `size` still *responds* to "
             "the raw price actually changing (a test that only asserts immobility would also "
             "pass if the feature were a constant).\n")
    L.append("* Fixing A-1 exposed a flaw in the test fixture itself: `close` and `adj_close` "
             "were identical in the synthetic panel, so one of the two tripwires had been "
             "passing **vacuously** — it could never have detected the change it existed to "
             "detect. The fixture now makes them differ.\n")

    L.append("---\n")
    L.append("## Arm 2 — XGBoost · *not yet run*\n")
    L.append("One controlled rival on identical features/labels/protocol, answering \"is it "
             "the library?\". AdaBoost is excluded by instruction: a superseded boosting "
             "family whose inclusion would add a multiple-testing cost for no new information. "
             "Ensembles only if an arm beats momentum on its own — losers are not ensembled.\n")
    L.append("## Arm 3 — long/short research book · *not yet run*\n")
    L.append("Decile long/short, market-neutral, same costs plus a documented borrow-cost "
             "assumption, scored by v2. A **research sleeve** — it does not compete for the "
             "product engine, because the retail pie stays long-only by product definition.\n")

    L.append("---\n")
    L.append("## Closure statement · *pending arms 2 and 3*\n")
    L.append(f"Arm 1 verdict: **momentum keeps the engine.** The clean v2 model loses on "
             f"after-cost Sharpe ({_n(ml2['sharpe'])} vs {_n(mom2['sharpe'])}) and fails the "
             f"consistency clause ({ver['ic_consistency']:.0%} of years). Under the "
             "pre-stated criterion that is not a marginal result to be revisited — it is the "
             "answer the criterion was written to produce.\n")

    REPORT_PATH.write_text("\n".join(L))
    return REPORT_PATH


def main():
    res = arm1(make_report=True)
    v = res["verdict"]
    print(f"Arm 1 — earns the engine: {v['ml_earns_keep']}")
    print(f"  {v['headline']}")
    print("report ->", res.get("report_path"))


if __name__ == "__main__":
    main()
